# Generated by Django 2.2.6 on 2020-03-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthplanportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthPlans',
            new_name='HealthPlan',
        ),
    ]
