# Generated by Django 2.2.6 on 2020-03-19 18:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chooseplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='Please_choose_all_that_apply',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('35', 'Depression/or other mental health conditions'), ('36', 'Respiratory Illnesses'), ('37', 'Heart Condition(s)'), ('38', 'Have dependencies'), ('39', 'Take prescription drugs'), ('40', 'Diabetes'), ('41', 'Physical condition(s)'), ('42', 'Chronic Condition(s)'), ('43', 'Disabled'), ('44', 'Serious illnesses and disorders(HIV/Aids, Cancer ,Influenza, Scoliosis, Epilepsy, etc..)')], default='Unspecified', max_length=100),
        ),
    ]
