from django.db import models
from hospital_services_portal.models import Hospital


class HealthPlan(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField('date added')
    Overall_deductible_person= models.IntegerField(blank=True, default=-1)
    Overall_deductible_family= models.IntegerField(blank=True, default=-1)
    Out_of_pocket_limit_person= models.IntegerField(blank=True, default=-1)
    Out_of_pocket_limit_family= models.IntegerField(blank=True, default=-1)
    Primary_care_visit = models.IntegerField(blank=True, default=-1)
    Primary_care_visit_Percentage = models.IntegerField(blank=True, default=-1)
    Specialist_visit = models.IntegerField(blank=True, default=-1)
    Specialist_visit_Percentage = models.IntegerField(blank=True, default=-1)
    Diagnostic_test_lab = models.IntegerField(blank=True, default=-1)
    Diagnostic_test_lab_Percentage = models.IntegerField(blank=True, default=-1)
    Diagnostic_test_xray = models.IntegerField(blank=True, default=-1)
    Diagnostic_test_xray_Percentage = models.IntegerField(blank=True, default=-1)
    Imaging = models.IntegerField(blank=True, default=-1)
    Imaging_Percentage = models.IntegerField(blank=True, default=-1)
    Generic_drugs_pescrciption = models.IntegerField(blank=True, default=-1)
    Generic_drugs_pescrciption_Percentage = models.IntegerField(blank=True, default=-1)
    Preffered_drugs_pescrciption = models.IntegerField(blank=True, default=-1)
    Preffered_drugs_pescrciption_Percentage = models.IntegerField(blank=True, default=-1)
    Facility_fee = models.IntegerField(blank=True, default=-1)
    Facility_fee_Percentage = models.IntegerField(blank=True, default=-1)
    Physician_surgeon_fee = models.IntegerField(blank=True, default=-1)
    Physician_surgeon_fee_Percentage = models.IntegerField(blank=True, default=-1)
    Emergency_room_care_IMA = models.IntegerField(blank=True, default=-1)
    Emergency_room_care_IMA_Percentage = models.IntegerField(blank=True, default=-1)
    Emergency_medical_transportation_IMA = models.IntegerField(blank=True, default=-1)
    Emergency_medical_transportation_IMA_Percentage = models.IntegerField(blank=True, default=-1)
    Urgent_care_IMA = models.IntegerField(blank=True, default=-1)
    Urgent_care_IMA_Percentage = models.IntegerField(blank=True, default=-1)
    Emergency_room_care_Hospital_Stay = models.IntegerField(blank=True, default=-1)
    Emergency_room_care_Hospital_Stay_Percentage = models.IntegerField(blank=True, default=-1)
    Emergency_medical_transportation_HospitalStay = models.IntegerField(blank=True, default=-1)
    Emergency_medical_transportation_HospitalStay_Percentage= models.IntegerField(blank=True, default=-1)
    Outpatient_services = models.IntegerField(blank=True, default=-1)
    Outpatient_services_Percentage = models.IntegerField(blank=True, default=-1)
    Inpatient_services = models.IntegerField(blank=True, default=-1)
    Inpatient_services_Percentage = models.IntegerField(blank=True, default=-1)
    Pregnant_childbirth_delivery_professional_services = models.IntegerField(blank=True, default=-1)
    Pregnant_childbirth_delivery_professional_services_Percentage = models.IntegerField(blank=True, default=-1)
    Pregnant_childbirth_delivery_facility_services = models.IntegerField(blank=True, default=-1)
    Pregnant_childbirth_delivery_facility_services_Percentage = models.IntegerField(blank=True, default=-1)
    Pregnant_office_visit = models.IntegerField(blank=True, default=-1)
    Pregnant_office_visit_Percentage = models.IntegerField(blank=True, default=-1)
    Home_health_care = models.IntegerField(blank=True, default=-1)
    Home_health_care_Percentage = models.IntegerField(blank=True, default=-1)
    Rehabilitation_services = models.IntegerField(blank=True, default=-1)
    Rehabilitation_services_Percentage = models.IntegerField(blank=True, default=-1)
    Skilled_nursing_care = models.IntegerField(blank=True, default=-1)
    Skilled_nursing_care_Percentage = models.IntegerField(blank=True, default=-1)
    Durable_medical_eqiupment = models.IntegerField(blank=True, default=-1)
    Durable_medical_eqiupment_Percentage = models.IntegerField(blank=True, default=-1)
    # hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
